### ISSUE TITLE
Fails to build from source on Fedora Rawhide

### ISSUE THREAD

**Issue by dmaphy** [b4n/ctpl#2]
I"m not very deep into the topic, what I understand is, that Fedora 41 will contain newer versions of C and glib2. The ctpl package in Fedora currently fails to build: https://koji.fedoraproject.org/koji/taskinfo?taskID=120645609

I think the relevant information needed to fix the issue, is in the `build.log`:

```
737:23: note: declared here
  737 | void                  g_type_init                    (void);
      |                       ^~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gbinding.h:31,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from /usr/include/glib-2.0/gio/gioenums.h:30,
                 from /usr/include/glib-2.0/gio/giotypes.h:30,
                 from /usr/include/glib-2.0/gio/gio.h:28,
                 from ctpl-output-stream.h:28,
                 from ctpl-output-stream.c:20:
ctpl-output-stream.c: In function 'ctpl_output_stream_new':
/usr/include/glib-2.0/gobject/gobject.h:533:28: error: returning 'GOutputStream *' {aka 'struct _GOutputStream *'} from a function with incompatible return type 'CtplOutputStream *' {aka 'struct _CtplOutputStream *'} [-Wincompatible-pointer-types]
  533 | #define g_object_ref(Obj) ((glib_typeof (Obj)) (g_object_ref) (Obj))
      |                           ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ctpl-output-stream.c:67:10: note: in expansion of macro 'g_object_ref'
   67 |   return g_object_ref (stream);
      |          ^~~~~~~~~~~~
make[2]: *** [Makefile:706: libctpl_la-ctpl-output-stream.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/ctpl-0.3.4-build/ctpl-0.3.4/src'
make[1]: *** [Makefile:456: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/ctpl-0.3.4-build/ctpl-0.3.4'
make: *** [Makefile:385: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.C9JzkU (%build)
    Bad exit status from /var/tmp/rpm-tmp.C9JzkU (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 8a8c5076b3fa4f10908cddaec8b0d8d7 -D /var/lib/mock/f41-build-52347311-6263043/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.o_qhk138:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin \'--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"\' \'--setenv=PS1=<mock-chroot> \\s-\\v\\$ \' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c \'/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/ctpl.spec\'\n', 1)]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mockbuild/util.py", line 612, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (cmd_pretty(command, env), output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 8a8c5076b3fa4f10908cddaec8b0d8d7 -D /var/lib/mock/f41-build-52347311-6263043/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.o_qhk138:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/ctpl.spec'
```

Hopefully that's something you can work with. Unfortunately, if we don't manage to fix this, the package will likely drop out of Fedora and thus, also the Geany-Plugin depending on it (which is geanygendoc for now).

Here is a link to the RedHat bugzilla as well:

https://bugzilla.redhat.com/show_bug.cgi?id=2300615

**Comment by b4n** [comment]
Should be fixed in master, I'll try to see for making a release tonight (no promises), but you can anyway backport the trivial build fix.

**Comment by dmaphy** [comment]
Thanks for this prompt reaction! I didn't expect the fix to be that easy. I would try a backport earliest tomorrow morning, so probably there is time for release until then anyway. (:

**Comment by cwendling** [comment]
Haha :)  Here you go, there's a fresh release, 9 years later!

**Comment by b4n** [comment]
Haha :) Here you go, there's a fresh release, 9 years later!

**Comment by dmaphy** [comment]
Just for completeness: The build worked without any issues and updates for Fedora 41 (Rawhide) are available:

https://koji.fedoraproject.org/koji/buildinfo?buildID=2521211
https://bodhi.fedoraproject.org/updates/FEDORA-2024-ccb39e0007
